import { createClient } from "@supabase/supabase-js";
import path from "path";
import dotenv from "dotenv";
import type { Database } from "../types/database.types"; // Generated by Supabase CLI

// Support both running from backend/ and from scripts/ subdirectory
const envPath = path.resolve(process.cwd(), ".env");
dotenv.config({ path: envPath });

// Fallback to process.env if already set (e.g., Docker/CI environment)
const supabaseUrl  = process.env.SUPABASE_URL  ?? "";
const supabaseKey  = process.env.SUPABASE_SERVICE_KEY ?? "";

if (!supabaseUrl || !supabaseKey) {
    console.warn(
        "[supabaseClient] WARNING: SUPABASE_URL or SUPABASE_SERVICE_KEY is not set. " +
        "Ensure .env is loaded before importing this module."
    );
}

// Export a strongly-typed client
export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
    global: {
        fetch: (url, init) => {
            return fetch(url, {
                ...init,
                // Increase the default timeout for the fetch request
                signal: AbortSignal.timeout(60000)
            });
        }
    }
});